"""products unit column added

Revision ID: 430662608cd1
Revises: 4cea76c4db32
Create Date: 2023-08-03 04:23:08.015561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430662608cd1'
down_revision = '4cea76c4db32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
