"""role

Revision ID: 4cea76c4db32
Revises: e95b423fc43d
Create Date: 2023-07-31 23:27:48.603705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cea76c4db32'
down_revision = 'e95b423fc43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
